# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
# app/config/services.yml
    app.post_voter:
        class: AppBundle\Security\StoryVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false